language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'


before_script:
- composer require php-coveralls/php-coveralls:^2.1.0
- composer install -n

deploy:
  provider: azure_web_apps
  username: "jsteimle"
  password: "5Pb14%lVAzMU714$iOKi"
  site: "hackatum2019-jakob"
  skip_cleanup: true

script:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi
