language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'


before_script:
- composer require php-coveralls/php-coveralls:^2.1.0
- composer install -n

env:
  global:
  - 'SFTP_USER=hackatum2019-jakob\$hackatum2019-jakob'
  - 'SFTP_PASSWORD=LoZLcxx7MsY3Mu8mWmPLd8WWnJB2iA29tSril8r5fFFiyfgmCoolAJPki4zN'
after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@waws-prod-am2-281.ftp.azurewebsites.windows.net/site/wwwroot

script:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi
